### ISSUE TITLE
Funkyness causing null pointer in pathfinding

### ISSUE THREAD

**Issue by import-antigravity** [cwruRobotics/NASA-RMC-2018#29]
I think this is setting positions to `(NaN, NaN)` when they should be `null` which is causing them to not get caught by the `if` statement:

https://github.com/cwruRobotics/NASA-RMC-2018/blob/649c35770872536636ed628608ee3c73ce0cf376/glennifer/automodule/src/test/PathPlanSimulator.java#L209

**Comment by jsh318900** [comment]
Issue fixed by pull request #30
